name: Debug (MacOS)

on: [workflow_dispatch]

jobs:
    debug:
      runs-on: macos-latest
      steps:
        - name: Checkout Zfp
          uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

        - name: Setup Python
          uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
          with:
            python-version: '3.x'
            architecture: x64

        - name: Install Zfpy Dependencies
          run: |
            python -m pip install cython
            python -m pip install oldest-supported-numpy
            python -m pip install setuptools

        - name: Install OpenMP
          run: |
            brew install libomp

        - name: Setup Tmate Session
          uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 # v3
