# Globally lock version of third party libraries
packages:
  axom:
    require:
    - spec: "@0.10.1.1"
  adiak:
    require:
    - spec: "@0.4.1"
  caliper:
    require:
    - spec: "@2.12.1"
  camp:
    require:
    - spec: "@2024.07.0"
  conduit:
    require:
    - spec: "@0.9.2"
  hypre:
    require:
    - spec: "@2.26.0"
  mfem:
    require:
    - spec: "@4.8.0.1"
  petsc:
    require:
    - spec: "@3.21.6"
  raja:
    require:
    - spec: "@2024.07.0"
  sundials:
    require:
    - spec: "@6.7.0"
  umpire:
    require:
    - spec: "@2024.07.0"