tutorial_name = "latest-tutorial"

[aws.eksctl]
cluster_name = "latest-tutorial"
cluster_deployment_region = "us-east-1"
cluster_availability_zones = [
    "us-east-1a",
    "us-east-1b",
]

[[aws.eksctl.cluster_node_groups]]
zone = "us-east-1a"
instance_type = "c7i.12xlarge"
volume_size = 30
desired_size = 15
min_size = 15
max_size = 100

[[aws.eksctl.cluster_node_groups]]
zone = "us-east-1b"
instance_type = "c7i.12xlarge"
volume_size = 30
desired_size = 15
min_size = 15
max_size = 100

[aws."Kubernetes autoscaler"]
cpu_max = "100m"
memory_max = "600Mi"
cpu_min = "100m"
memory_min = "600Mi"

[aws.Helm]
max_concurrent_users = 30
hub_password = "hpctutorial25"
hub_db_capacity = "32Gi"
ebs_storage_type = "gp3"
use_nginx = true
hub_container_image = "jupyterhub/k8s-hub"
hub_container_tag = "4.2.0"
spawner_container_image = "ghcr.io/llnl/reproducible-benchmarking-spawn"
spawner_container_tag = "latest"
spawner_image_entrypoint = "/entrypoint.sh 32"
cpu_min = "32"
cpu_max = "32"
mem_min = "64G"
mem_max = "64G"
provide_extra_shmem = true
init_container_image = "ghcr.io/llnl/reproducible-benchmarking-init"
init_container_tag = "latest"
init_image_entrypoint = "/entrypoint.sh"

[aws."utility scripts"]
jupyterhub_helm_version = "4.2.0"
ebs_csidriver_version = "v1.45.0"
