out_dir: results
train:  
    epochs: 600
    batch_size: 4
    train_val_ratio: 1.0
model:
    file_name: 'snap_model_d2_k6'
    pooling_rate: -1.0
    fixed_rate_l: 0.8
    num_kernels: 6
    channels: ('90,90')
    edge_reduction: 'score_adaptive'
optim:
    lr: 5e-4
dataset:
    elem: 'Ta'
    feature_type: 'snap_all'
test:
    xyz_dir : 'test_d2_k6'
