[project]
name = "svg2contours"
version = "0.1.0"
description = "Environment for running svg2contours script"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "svgpathtools>=1.7.2",
]
