capture_probes:
  - name: vol
    probe: uprobe
    type: binary
    file: /home/haridev/spack/opt/spack/linux-haswell/hdf5-1.14.5-ul6ejhuh527dwwbgwi3ij6soj2pikw2u/lib/libhdf5.so
    regex: H5VL.*
  - name: h5ac
    probe: uprobe
    type: binary
    file: /home/haridev/spack/opt/spack/linux-haswell/hdf5-1.14.5-ul6ejhuh527dwwbgwi3ij6soj2pikw2u/lib/libhdf5.so
    regex: H5AC.*
  - name: h5a
    probe: uprobe
    type: binary
    file: /home/haridev/spack/opt/spack/linux-haswell/hdf5-1.14.5-ul6ejhuh527dwwbgwi3ij6soj2pikw2u/lib/libhdf5.so
    regex: H5A(?!C).*
  - name: h5b
    probe: uprobe
    type: binary
    file: /home/haridev/spack/opt/spack/linux-haswell/hdf5-1.14.5-ul6ejhuh527dwwbgwi3ij6soj2pikw2u/lib/libhdf5.so
    regex: H5B.*
  - name: h5d
    probe: uprobe
    type: binary
    file: /home/haridev/spack/opt/spack/linux-haswell/hdf5-1.14.5-ul6ejhuh527dwwbgwi3ij6soj2pikw2u/lib/libhdf5.so
    regex: H5D.*
  - name: h5f
    probe: uprobe
    type: binary
    file: /home/haridev/spack/opt/spack/linux-haswell/hdf5-1.14.5-ul6ejhuh527dwwbgwi3ij6soj2pikw2u/lib/libhdf5.so
    regex: H5F.*
  # - name: h5general
  #   probe: uprobe
  #   type: binary
  #   file: /home/haridev/spack/opt/spack/linux-haswell/hdf5-1.14.5-ul6ejhuh527dwwbgwi3ij6soj2pikw2u/lib/libhdf5.so
  #   regex: H5_.*
  # - name: h5i
  #   probe: uprobe
  #   type: binary
  #   file: /home/haridev/spack/opt/spack/linux-haswell/hdf5-1.14.5-ul6ejhuh527dwwbgwi3ij6soj2pikw2u/lib/libhdf5.so
  #   regex: H5I.*
  - name: h5t
    probe: uprobe
    type: binary
    file: /home/haridev/spack/opt/spack/linux-haswell/hdf5-1.14.5-ul6ejhuh527dwwbgwi3ij6soj2pikw2u/lib/libhdf5.so
    regex: H5T.*
  - name: h5s
    probe: uprobe
    type: binary
    file: /home/haridev/spack/opt/spack/linux-haswell/hdf5-1.14.5-ul6ejhuh527dwwbgwi3ij6soj2pikw2u/lib/libhdf5.so
    regex: H5S.*
  # - name: mpi
  #   probe: uprobe
  #   type: binary
  #   file: /usr/lib/x86_64-linux-gnu/libmpi.so.40
  #   regex: .*    
  # - name: h5bench
  #   probe: uprobe
  #   type: binary
  #   file: /home/cc/apps/h5bench/bin/h5bench_write
  #   regex: ^(?!__).*