capture_probes:
  - name: mpi-api
    probe: uprobe
    type: binary
    file: /opt/cray/pe/lib64/libmpi_cray.so.12
    regex: PMPI.*
  - name: mpii
    probe: uprobe
    type: binary
    file: /opt/cray/pe/lib64/libmpi_cray.so.12
    regex: MPII.*
  - name: mpi-rest
    probe: uprobe
    type: binary
    file: /opt/cray/pe/lib64/libmpi_cray.so.12
    regex: .*