name: ðŸ§¹ clang-tidy

on:
  push:
    branches:
      - "development"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-clangtidy
  cancel-in-progress: true

jobs:

  check_changes:
    name: Analyze
    uses: ./.github/workflows/check_changes.yml

  run_clang_tidy:
    strategy:
      matrix:
        dim: [1, 2, RZ, 3]
    name: clang-tidy-${{ matrix.dim }}D
    runs-on: ubuntu-24.04
    timeout-minutes: 250
    needs: check_changes
    if: ${{ github.event.pull_request.draft == false }}
    steps:
    - uses: actions/checkout@v4
      if: ${{ needs.check_changes.outputs.has_non_docs_changes == 'true' }}
    - name: install dependencies
      if: ${{ needs.check_changes.outputs.has_non_docs_changes == 'true' }}
      run: |
        .github/workflows/dependencies/clang.sh 17
    - name: set up cache
      if: ${{ needs.check_changes.outputs.has_non_docs_changes == 'true' }}
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache
        key: ccache-${{ github.workflow }}-${{ github.job }}-git-${{ github.sha }}
        restore-keys: |
             ccache-${{ github.workflow }}-${{ github.job }}-git-
    - name: build WarpX & run clang-tidy
      if: ${{ needs.check_changes.outputs.has_non_docs_changes == 'true' }}
      run: |
        export CCACHE_COMPRESS=1
        export CCACHE_COMPRESSLEVEL=10
        export CCACHE_MAXSIZE=300M
        export CCACHE_EXTRAFILES=${{ github.workspace }}/.clang-tidy
        export CCACHE_LOGFILE=${{ github.workspace }}/ccache.log.txt
        ccache -z
        export CXX=$(which clang++-17)
        export CC=$(which clang-17)
        cmake -S . -B build_clang_tidy      \
          -DCMAKE_VERBOSE_MAKEFILE=ON       \
          -DWarpX_DIMS="${{ matrix.dim }}"  \
          -DWarpX_MPI=ON                    \
          -DWarpX_COMPUTE=OMP               \
          -DWarpX_FFT=ON                    \
          -DWarpX_QED=ON                    \
          -DWarpX_QED_TABLE_GEN=ON          \
          -DWarpX_OPENPMD=ON                \
          -DWarpX_PRECISION=SINGLE          \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build build_clang_tidy -j 4
        ${{github.workspace}}/.github/workflows/source/makeMakefileForClangTidy.py --input ${{github.workspace}}/ccache.log.txt
        make -j4 --keep-going -f clang-tidy-ccache-misses.mak \
            CLANG_TIDY=clang-tidy-17 \
            CLANG_TIDY_ARGS="--config-file=${{github.workspace}}/.clang-tidy --warnings-as-errors=*"
        ccache -s
        du -hs ~/.cache/ccache
