# run this with codepy run . -c codepy_config_list.yaml

setup:
  interactive: true
  sleep: 1
  autoyes: true
  study_name: list
  sampler:
    type: list
    constants:
      X1: 20
      s_type: list
    parameters:
      X2: [5, 10]
      X3: [5, 10]