device: "cuda:0"
model: combo 
embedding: molformer-decfp-combo 
ecfp_length: 1000
ecfp_radius: 4
input_size: 768 
D: 1000
sim_metric: cosine
binarize_am: False
binarize_hv: False
bipolarize_am: False
bipolarize_hv: True
num_workers: 0 