#
# This file lists the package versions for axom's dependencies
#

packages:
  adiak:
    require: 
      - spec: "@0.4.0"
  # 7/23/25 - Commit after 2.13.1 release, has fix for CUDA 12.9.1
  caliper:
    require:
      - spec: "@git.527e1ae3a16487e425707e928e05c43d372e144f=master"
  camp:
    require:
      - spec: "@2025.09.2"
  conduit:
    require:
      - spec: "@0.9.5"
  hypre:
    require:
      - spec: "@2.27.0"
  mfem:
    require:
      - spec: "@4.9"
  opencascade:
    require:
      - spec: "@7.8.1"
  py-jsonschema:
    require:
      - spec: "@:4.17" #Anything after this requires py-rpds which requires rust and adds 40 minutes
  raja:
    require:
      - spec: "@2025.09.0"
  scr:
    require:
      - spec: "@3.0.1"
  umpire:
    require:
      - spec: "@2025.09.0"
