name: Pull Request Quality Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f py/requirements.txt ]; then pip install -r py/requirements.txt; fi
          if [ -f py/requirements-dev.txt ]; then pip install -r py/requirements-dev.txt; fi

      - name: Lint with ruff
        run: |
          cd py
          ruff check src/clippy --output-format=concise --statistics --line-length=120


      - name: MyPy
        run: |
          cd py
          mypy src/clippy --ignore-missing-imports

      - name: Install Boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.83.0
          # OPTIONAL: Specify a platform version
          # platform_version: 18.04
          # OPTIONAL: Specify a custom install location
          # boost_install_dir: /home/runner/work/boost
          # OPTIONAL: Specify a toolset
          toolset: gcc
          # OPTIONAL: Specify an architecture
          # arch: x86

      # - name: Setup ccache
      #   uses: hendrikmuhs/ccache-action@v1.2
      #   with:
      #     key: ${{ github.job }}-${{ runner.os }}
      #     max-size: 500M  # limit cache size
      - name: Build backend
        id: build-backend
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        run: |
          echo BOOST_ROOT is $BOOST_ROOT /end/
          sudo apt install -y doxygen
          CPPDIR=cpp
          mkdir -p $CPPDIR/build
          cd $CPPDIR/build && cmake -DMODERN_CMAKE_BUILD_TESTING=ON -DBUILD_TESTING=ON -DBOOST_ROOT=$BOOST_ROOT .. && make 
          ls -l examples
          BACKEND=$CPPDIR/build/examples
          # echo "BACKEND=$BACKEND" >> $GITHUB_ENV

      - name: Pytest
        run: |
          cd test
          ./run_tests.sh
      # - name: Pytest
      #   run: |
      #     coverage run --source clippy/ -m pytest && coverage report -m --fail-under 99
