[default]
redactkeys = [
    "Name",
    "Names",
    "Site",
    "Running",
    "DeviceID",
    "Area",
    "Organization",
    "Type",
    "Continent",
    "Country",
    "Customers",
    "Size",
]

[assetData]
redactkeys = [
    "Brand",
    "Category",
    "DataSources",
    "DeviceID",
    "FirmwareID",
    "Name",
    "Names",
    "Roles",
    "Site",
    "Type",
]

[orgData]
redactkeys = [
    "OrgId",
    "Organization",
    "Type",
    "Continent",
    "Country",
    "Area",
    "Customers",
    "Size",
    "CISector",
]

[testAll]
redactkeys = [ 'Name', 'Names', 'Make','FirmwareVersion' ]
redactvalues = [ ["Brand","Cisco.*"], ["Model","SEL.*"] ]
redactrecords = [ ["Brand","GE.*"], ["Model","Other.*"] ]
redactvaluesforkey = [ [ "Name","Arbiter.1133A.*","Make,Model,FirmwareVersion,Site"], ["Make","This.*","Make,Model,FirmwareVersion"] ]

[test]
redactkeys = [ 'Name', 'Names', 'Make','FirmwareVersion' ]
redactvalues = [ ["Brand","Cisco.*"], ["Model","SEL.*"] ]


