on:
  workflow_call:
    inputs:
      modified_repo_dirs:
        required: true
        type: string
jobs:
  diffPackages:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Add needed Python libs
        run: |
          pip install -r ./requirements.txt
      - name: Check Packages Against Spack
        run: |-
          ./bin/benchpark-python lib/scripts/diffPackageCommits.py --packages "${{ inputs.modified_repo_dirs }}"
