name: License Checks
on:
  workflow_call:
jobs:
  verify-license:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Set up Python 3.11
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: '3.11'
      - name: Verify license headers
        run: |-
          python .github/workflows/bin/license verify
