name: Linting & Style Checks
on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: Set up Python 3.11
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: .github/workflows/requirements/style.txt
      - name: Install Python dependencies
        run: |
          pip install -r .github/workflows/requirements/style.txt
      - name: Lint and Format Check
        run: |-
          black --diff --check .
          codespell --ignore-words=.codespellignore
          isort --check-only .
          flake8 .
          yamlfix --check --verbose .
          docstrfmt -p .github/workflows/requirements/docstrfmt.toml --check --verbose --ignore-cache docs/
