tutorial_name = "hpdc-2025-pave-dry-run"

[aws.eksctl]
cluster_name = "hpdc-2025-pave-dry-run"
cluster_deployment_region = "us-west-1"
cluster_availability_zones = [
    "us-west-1a",
    "us-west-1c",
]

[[aws.eksctl.cluster_node_groups]]
zone = "us-west-1a"
instance_type = "c7i.12xlarge"
volume_size = 30
desired_size = 2
min_size = 2
max_size = 8

[[aws.eksctl.cluster_node_groups]]
zone = "us-west-1c"
instance_type = "c7i.12xlarge"
volume_size = 30
desired_size = 2
min_size = 2
max_size = 8

[aws."Kubernetes autoscaler"]
cpu_max = "100m"
memory_max = "600Mi"
cpu_min = "100m"
memory_min = "600Mi"

[aws.Helm]
max_concurrent_users = 14
hub_password = "hpctutorial25"
hub_db_capacity = "32Gi"
ebs_storage_type = "gp3"
hub_container_image = "jupyterhub/k8s-hub"
hub_container_tag = "4.2.0"
spawner_container_image = "ghcr.io/llnl/reproducible-benchmarking-spawn"
spawner_container_tag = "hpdc-2025"
spawner_image_entrypoint = "/entrypoint.sh"
cpu_min = "32"
cpu_max = "32"
mem_min = "64G"
mem_max = "64G"
provide_extra_shmem = true
init_container_image = "ghcr.io/llnl/reproducible-benchmarking-init"
init_container_tag = "hpdc-2025"
init_image_entrypoint = "/entrypoint.sh"
custom_host = "https://software.llnl.gov/benchpark/hpdc-25-tutorial"

[aws."utility scripts"]
jupyterhub_helm_version = "4.2.0"
ebs_csidriver_version = "v1.45.0"
