[package]
name = "xtal_light_up"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {version="1.0"}
# rayon = {version="1.10"}
numpy = {version = "0.21", optional=false}
pyo3 = { version = "0.21", optional=false, features = ["abi3-py39", "extension-module","anyhow", "multiple-pymethods",] }

num-traits = {version = "0.2.14", features = ["libm"]}
[features]
# python = ["numpy", "pyo3"]

[lib]
name = "xtal_light_up"
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

[profile.test]
opt-level = 1
debug = false
lto = true
incremental = false
codegen-units = 1
