name: CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: cargo build --verbose

    - name: Upload dapper binary
      uses: actions/upload-artifact@v6
      with:
        name: dapper-binary-${{ runner.os }}
        path: |
          target/debug/dapper${{ matrix.os == 'windows-latest' && '.exe' || '' }}

    - name: Run tests
      run: cargo test --verbose

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Run Clippy
      run: |
        cargo clippy --version
        cargo clippy -- -D warnings

  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Check formatting
      run: |
        cargo fmt --version
        cargo fmt -- --check

  python-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
      working-directory: python

    - name: Run pytest
      run: python -m pytest
      working-directory: python
  
  fetching-dataset-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v6
    - name: Download dapper dataset
      uses: actions/download-artifact@v7
      with:
        name: dapper-binary-${{ runner.os }}
        path: target/debug/

    - name: Make binary executable
      run: chmod +x target/debug/dapper

    - name: Download and Extract dataset
      env:
        #Points at file for the current branch/PR, if this doesn't work we could also try relative filepath
        DAPPER_DATASET_MANIFEST: https://raw.githubusercontent.com/LLNL/dapper/${{ github.ref }}/docs/dataset_list.toml
      run: |
        # Initializing XDG directory
        mkdir -p $HOME/.local/share/dapper

        # Download Linux package database
        ./target/debug/dapper db install ubuntu-jammy

        # Download PyPI package database
        ./target/debug/dapper db install pypi

    - name: Test Dapper with downloaded artifact
      run: |
        mkdir -p /tmp/test-files
        echo '#include <iostream>' > /tmp/test-files/test.cpp

        ./target/debug/dapper /tmp/test-files
