# run this with codepy run . -c codepy_config_random.yaml

setup:
  interactive: true
  sleep: 1
  autoyes: true
  study_name: random
  sampler:
    type: random
    num_samples: 2
    constants:
      X1: 20
      s_type: random
    parameters:
      X2:
        min: 5
        max: 10
      X3:
        min: 5
        max: 10