# Globally lock version of third party libraries
packages:
  axom:
    require:
    - spec: "@0.12.0.0"
  adiak:
    require:
    - spec: "@0.4.1"
  caliper:
    require:
    - spec: "@2.12.1"
  camp:
    require:
    - spec: "@2025.09.2"
  conduit:
    require:
    - spec: "@0.9.5"
  mfem:
    require:
    - spec: "@4.9.0.2"
  petsc:
    require:
    - spec: "@3.21.6"
  raja:
    require:
    - spec: "@2025.09.0"
  sundials:
    require:
    - spec: "@6.7.0"
  tribol:
    require:
    - spec: "@0.1.0.23"
  umpire:
    require:
    - spec: "@2025.09.0"
