name: Security Checks
on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      # https://bandit.readthedocs.io/en/latest/faq.html#under-which-version-of-python-should-i-install-bandit
      - name: Set up Python 3.10
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '.github/workflows/requirements/security.txt'

      - name: Install Python dependencies
        run: pip install -r .github/workflows/requirements/security.txt

      - name: Run Bandit
        run: bandit -c pyproject.toml -r src -f sarif -o results.sarif

      # upload security results to github; a bot will add inline comments to
      # the PR if any issues are found
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89
        with:
          sarif_file: results.sarif
          category: bandit

  codeql-analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [actions, python]
    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

    - name: Initialize CodeQL
      uses: github/codeql-action/init@cdefb33c0f6224e58673d9004f47f7cb3e328b89
      with:
        languages: ${{ matrix.language }}
        build-mode: none

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@cdefb33c0f6224e58673d9004f47f7cb3e328b89
      with:
        category: "/language:${{matrix.language}}"
